### ISSUE TITLE
Re-running command

### ISSUE THREAD

**Issue by GitHubGreg** [ahmadawais/WP-Salts-Update-CLI#1]
Thanks for this excellent contribution. I ran it and it worked well. 

However, I tried running it again (to re-update the salts) and it just shows this, without re-updating the salts: 

```
--------------- ⏲  LET' START... ---------------
-
 --------------------------------------------------------
 --------------- ✔︎✔︎✔︎ ALL DONE!  🎉 ✔✔✔ ---------------
 --------------------------------------------------------
```

**Comment by ahmadawais** [comment]
@GitHubGreg Glad you liked it.

I will take another look at it.

**Comment by ahmadawais** [comment]
Just tested it, and it works fine.

@GitHubGreg 


If for some reason the script doesn't work, you might want to check what is the output of this command 
`find . -name wp-config.php -print` this command should print the paths for all the wp-config.php files present inside your current directory or directories within it. If it doesn't display the paths, then you're probably at the wrong folder E.g. `cd ~` or `/root` — so just  `cd /` and then run `wpsucli`.
